export const TransactionsActionTypes = {
  GET_LIST_TRANSACTIONS: "GET_LIST_TRANSACTIONS",
  GET_USER_INFO: "GET_USER_INFO",
  GET_FILTERED_USER_LIST: "GET_FILTERED_USER_LIST",
  SET_ERROR: "SET_ERROR",
};
